# Generated by Django 5.1.3 on 2026-02-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imagepost_image_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
