# Generated by Django 5.1.3 on 2026-02-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_imagepost_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
